import 'dart:typed_data';

/// A dense vector generated by an embedding model.
class Embedding {
  Embedding(Float32List values) : values = Float32List.fromList(values) {
    if (values.isEmpty) {
      throw ArgumentError.value(values, 'values', 'must not be empty');
    }
  }

  final Float32List values;

  int get dimensions => values.length;
}
